import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import Header from "./components/organisms/Header";
import Confirmation from "./components/atoms/Confirmation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "StudioPresto Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <Confirmation />
          <Header />
          {children}
        </body>
      </Providers>
    </html>
  );
}
